id: P009200
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD17648
  title: རྒྱ་ཀོང་རིག་འཛིན་མཐར་ཕྱིན་གྱིས་ལམ་སང་བྲིས་པའི་སྙན་རྩོམ།
  author: ''
  volumes:
    7af79b712b634fd5adfff87b17e2033d:
      image_group_id: I2PD19249
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
