id: I97CCE17A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:55:45+00:00'
last_modified: '2022-06-08T09:19:53.617432+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17648
  title: རྒྱ་ཀོང་རིག་འཛིན་མཐར་ཕྱིན་གྱིས་ལམ་སང་བྲིས་པའི་སྙན་རྩོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    198F:
      image_group_id: I2PD19249
      title: ''
      total_pages: 208
      order: 1
      base_file: 198F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
